apiVersion: v1
kind: ConfigMap
metadata:
  name: freeimage-config
  namespace: freeimage
data:
  MONGO_URI: mongodb://mongo-service:27017/minifyurl
  NEXTAUTH_URL: http://20.244.0.167:3000
  NEXTAUTH_SECRET: password_nextauth
  CLOUDINARY_CLOUD_NAME: 
  CLOUDINARY_API_KEY: 
  CLOUDINARY_API_SECRET: 