apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:               
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/azureuser/freeimage_storage
  persistentVolumeReclaimPolicy: Retain
